/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.CaracteristicasDAO;
import JavaBeans.Caracteristicas;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author heito
 */
public class NovaCaracteristica extends javax.swing.JInternalFrame {

    /**
     * Creates new form NovaCaracteristica
     */
    public NovaCaracteristica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcaracteristica = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nova Característica");

        jLabel1.setText("Nova Característica");

        txtcaracteristica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaracteristicaActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcaracteristica))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 490, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcaracteristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtcaracteristica.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this.rootPane, "Preencha o campo Nova Característica");
        } else {
            try {
                // botão salvar
                Caracteristicas obj = new Caracteristicas();
                obj.setCaracteristicas(txtcaracteristica.getText());

                //objeto caracteristicasDAO
                CaracteristicasDAO dao = new CaracteristicasDAO();
                dao.cadastrarCaracteristicas(obj);

                JOptionPane.showMessageDialog(this.rootPane, "Caracteristica cadastrada com sucesso");
            } catch (Exception erro) {
                System.out.println(erro);
                JOptionPane.showMessageDialog(this.rootPane, erro);
            }
            //limpar tela
            for (int i = 0; i < getContentPane().getComponentCount(); i++) {
                Component c = getContentPane().getComponent(i);
                if (c instanceof JTextField) {
                    JTextField field = (JTextField) c;
                    field.setText("");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void txtcaracteristicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaracteristicaActionPerformed
        // TODO add your handling code here:
        if (txtcaracteristica.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this.rootPane, "Preencha o campo Nova Característica");
        } else {
            try {
                // botão salvar
                Caracteristicas obj = new Caracteristicas();
                obj.setCaracteristicas(txtcaracteristica.getText());

                //objeto caracteristicasDAO
                CaracteristicasDAO dao = new CaracteristicasDAO();
                dao.cadastrarCaracteristicas(obj);

                JOptionPane.showMessageDialog(this.rootPane, "Caracteristica cadastrada com sucesso");
            } catch (Exception erro) {
                System.out.println(erro);
                JOptionPane.showMessageDialog(this.rootPane, erro);
            }
            //limpar tela
            for (int i = 0; i < getContentPane().getComponentCount(); i++) {
                Component c = getContentPane().getComponent(i);
                if (c instanceof JTextField) {
                    JTextField field = (JTextField) c;
                    field.setText("");
                }
            }
        }
    }//GEN-LAST:event_txtcaracteristicaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtcaracteristica;
    // End of variables declaration//GEN-END:variables
}
