/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.FilhotesDAO;
import DAO.MatrizesDAO;
import java.awt.Dimension;
import JDBC.ConnectionFactory;
import JavaBeans.Filhotes;
import JavaBeans.Matrizes;
import Utilitários.UpperCaseField;
import java.awt.Component;
import java.sql.Connection;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author heito
 */
public class NovoFilhote extends javax.swing.JInternalFrame {

    private final Connection conecta;

    SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form NovoFilhote
     */
    public NovoFilhote() {
        this.conecta = new ConnectionFactory().conecta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        txtnome = new Utilitários.UpperCaseField();
        jLabel2 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcaracteristicas = new Utilitários.UpperCaseField();
        jLabel4 = new javax.swing.JLabel();
        txtdatanascimento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtproprietario = new Utilitários.UpperCaseField();
        jLabel8 = new javax.swing.JLabel();
        txtsituacao = new Utilitários.UpperCaseField();
        jLabel6 = new javax.swing.JLabel();
        txtnomepaimae = new Utilitários.UpperCaseField();
        jLabel7 = new javax.swing.JLabel();
        txtnomemaemae = new Utilitários.UpperCaseField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtdatanascimentofilhote = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtsexo = new UpperCaseField();
        jLabel11 = new javax.swing.JLabel();
        txtpai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtdatadesmama = new javax.swing.JFormattedTextField();
        botaosair = new javax.swing.JButton();
        botaosalvar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobservacao = new javax.swing.JTextArea();
        cmbsituacao = new javax.swing.JComboBox<>();
        txtcodigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jScrollPane2.setViewportView(jEditorPane1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Novo Filhote");

        jLabel1.setText("Nome");

        txtnome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnomeFocusLost(evt);
            }
        });
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Número");

        txtnumero.setEditable(false);
        txtnumero.setBackground(new java.awt.Color(204, 204, 204));
        txtnumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumero.setFocusable(false);

        jLabel3.setText("Características");

        txtcaracteristicas.setEditable(false);
        txtcaracteristicas.setBackground(new java.awt.Color(204, 204, 204));
        txtcaracteristicas.setFocusable(false);

        jLabel4.setText("Data de Nascimento");

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            txtdatanascimento.setEditable(false);
            txtdatanascimento.setBackground(new java.awt.Color(204, 204, 204));
            txtdatanascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
            txtdatanascimento.setFocusable(false);
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Proprietário");

        txtproprietario.setEditable(false);
        txtproprietario.setBackground(new java.awt.Color(204, 204, 204));
        txtproprietario.setFocusable(false);

        jLabel8.setText("Situação");

        txtsituacao.setEditable(false);
        txtsituacao.setBackground(new java.awt.Color(204, 204, 204));
        txtsituacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsituacao.setFocusable(false);

        jLabel6.setText("Nome do Pai");

        txtnomepaimae.setEditable(false);
        txtnomepaimae.setBackground(new java.awt.Color(204, 204, 204));
        txtnomepaimae.setFocusable(false);

        jLabel7.setText("Nome da Mãe");

        txtnomemaemae.setEditable(false);
        txtnomemaemae.setBackground(new java.awt.Color(204, 204, 204));
        txtnomemaemae.setFocusable(false);

        jLabel10.setText("Data de Nascimento");

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            txtdatanascimentofilhote.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
            txtdatanascimentofilhote.setPreferredSize(new java.awt.Dimension(4, 26));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatanascimentofilhote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdatanascimentofilhoteFocusLost(evt);
            }
        });

        jLabel12.setText("Sexo");

        txtsexo.setNextFocusableComponent(txtpai);
        txtsexo.setOpaque(false);

        jLabel11.setText("Nome do Pai");

        txtpai.setNextFocusableComponent(txtdatadesmama);

        jLabel13.setText("Previsão de Desmama");

        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            txtdatadesmama.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mascara));
            txtdatadesmama.setPreferredSize(new java.awt.Dimension(4, 26));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaosair.setText("Sair");
        botaosair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosairActionPerformed(evt);
            }
        });

        botaosalvar.setText("Salvar");
        botaosalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaosalvarActionPerformed(evt);
            }
        });

        jLabel14.setText("Dados do Filhote");

        jLabel15.setText("Observação");

        txtobservacao.setColumns(20);
        txtobservacao.setRows(5);
        jScrollPane1.setViewportView(txtobservacao);

        cmbsituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "DE", "MO", "VE", "SU" }));

        txtcodigo.setEditable(false);
        txtcodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtcodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcodigo.setCaretColor(new java.awt.Color(51, 51, 51));
        txtcodigo.setDragEnabled(true);
        txtcodigo.setFocusable(false);
        txtcodigo.setVisible(false);

        jLabel16.setText("Código");
        jLabel16.setVisible(false);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Dados da Mãe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnomemaemae, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtproprietario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomepaimae, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txtcaracteristicas))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigo)
                            .addComponent(txtnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtdatanascimento)
                            .addComponent(txtsituacao, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(219, 219, 219))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtdatanascimentofilhote, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtpai)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtdatadesmama, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaosalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaosair)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtcaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdatanascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtproprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnomepaimae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnomemaemae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaosair)
                            .addComponent(botaosalvar))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdatanascimentofilhote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtpai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtdatadesmama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    private void botaosairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosairActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaosairActionPerformed

    private void txtnomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusLost
        if (txtnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this.rootPane, "Insira o nome da matriz");
            txtnome.grabFocus();
        }
        try {
            String nome = txtnome.getText();
            MatrizesDAO dao = new MatrizesDAO();
            FilhotesDAO daof = new FilhotesDAO();
            List<Matrizes> lista = dao.nomeMae(nome);

            for (Matrizes mae : lista) {

                txtnumero.setText(mae.getNumero());
                txtcaracteristicas.setText(mae.getCaracteristicas());
                txtdatanascimento.setText(mae.getDatanascimento());
                txtproprietario.setText(mae.getProprietario());
                txtsituacao.setText(mae.getSituacao());
                txtnomepaimae.setText(mae.getNomepai());
                txtnomemaemae.setText(mae.getNomemae());
                txtcodigo.setText(Integer.toString(mae.getIdmatriz()));
            }
            List<Filhotes> listaFilhotes = daof.pesquisaMae(Integer.parseInt(txtcodigo.getText()));
            for (int i = 0; i < listaFilhotes.size(); i++) {
   
                if (listaFilhotes.get(i).getSituacao().equals("NO")) {
                    int resposta = JOptionPane.showConfirmDialog(this.rootPane, "Esta matriz possui um filhote em situação normal! Deseja cadastrar um novo filhote?", title, JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {

                    } else {
                        txtnome.grabFocus();
                        //limpar tela
                        for (int j = 0; j < getContentPane().getComponentCount(); j++) {
                            Component c = getContentPane().getComponent(j);
                            if (c instanceof JTextField) {
                                JTextField field = (JTextField) c;
                                field.setText("");
                            }
                        }
                    }
                }
            }

            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this.rootPane, "Matriz não cadastrada");
                txtnome.grabFocus();
                //limpar tela
                for (int i = 0; i < getContentPane().getComponentCount(); i++) {
                    Component c = getContentPane().getComponent(i);
                    if (c instanceof JTextField) {
                        JTextField field = (JTextField) c;
                        field.setText("");
                    }
                }
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_txtnomeFocusLost

    private void txtnomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnomeFocusGained
        //limpar tela
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            Component c = getContentPane().getComponent(i);
            if (c instanceof JTextField) {
                JTextField field = (JTextField) c;
                field.setText("");
            }
        }
    }//GEN-LAST:event_txtnomeFocusGained

    private void botaosalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaosalvarActionPerformed
        try {

            //1 passo - guardar os dados da tela no obj filhotes
            Filhotes obj = new Filhotes();
            obj.setNumero(txtnumero.getText());
            obj.setNome(txtnome.getText());
            obj.setCaracteristicas(txtcaracteristicas.getText());
            obj.setDatanascimentomae(txtdatanascimento.getText());
            obj.setProprietario(txtproprietario.getText());
            obj.setNomepaimae(txtnomepaimae.getText());
            obj.setNomemaemae(txtnomemaemae.getText());
            obj.setSituacaomae(txtsituacao.getText());
            obj.setIdmatriz(Integer.parseInt(txtcodigo.getText()));
            Date data = formatoData.parse(txtdatanascimentofilhote.getText());
            java.sql.Date dataSql = new java.sql.Date(data.getTime());
            obj.setDatanascimento(dataSql);
            obj.setSexo(txtsexo.getText());
            obj.setNomepai(txtpai.getText());
            Date dataD = formatoData.parse(txtdatadesmama.getText());
            java.sql.Date dataDSql = new java.sql.Date(dataD.getTime());
            obj.setDatadesmama(dataDSql);
            obj.setSituacao((String) cmbsituacao.getSelectedItem());
            obj.setObservacao(txtobservacao.getText());

            //2 pass0 - criar objeto do tipo FilhotesDAO
            FilhotesDAO dao = new FilhotesDAO();
            dao.cadastrarFilhotes(obj);

            JOptionPane.showMessageDialog(this.rootPane, "Filhote Cadastrado com sucesso");
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this.rootPane, "Erro, fale com seu programador");
        }
        //Limpar tela
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            Component c = getContentPane().getComponent(i);
            if (c instanceof JTextField) {
                JTextField field = (JTextField) c;
                field.setText("");
            }
        }
    }//GEN-LAST:event_botaosalvarActionPerformed

    private void txtdatanascimentofilhoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdatanascimentofilhoteFocusLost
        try {
            // TODO add your handling code here:
            GregorianCalendar calendar = new GregorianCalendar();
            String dataN = txtdatanascimentofilhote.getText();
           
            Date data = formatoData.parse(dataN);
            
            calendar.setTime(data);
            calendar.add(Calendar.MONTH, 9);
            txtdatadesmama.setText(formatoData.format(calendar.getTime()));

        } catch (ParseException ex) {
            Logger.getLogger(NovoFilhote.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_txtdatanascimentofilhoteFocusLost

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
        if (txtnome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this.rootPane, "Insira o nome da matriz");
            txtnome.grabFocus();
        }
        try {
            String nome = txtnome.getText();
            MatrizesDAO dao = new MatrizesDAO();
            List<Matrizes> lista = dao.nomeMae(nome);

            for (Matrizes mae : lista) {

                txtnumero.setText(mae.getNumero());
                txtcaracteristicas.setText(mae.getCaracteristicas());
                txtdatanascimento.setText(mae.getDatanascimento());
                txtproprietario.setText(mae.getProprietario());
                txtsituacao.setText(mae.getSituacao());
                txtnomepaimae.setText(mae.getNomepai());
                txtnomemaemae.setText(mae.getNomemae());
                txtcodigo.setText(Integer.toString(mae.getIdmatriz()));
                txtdatanascimentofilhote.grabFocus();
            }
            if (lista.isEmpty()) {
                JOptionPane.showMessageDialog(this.rootPane, "Matriz não cadastrada");
                txtnome.grabFocus();
                //limpar tela
                for (int i = 0; i < getContentPane().getComponentCount(); i++) {
                    Component c = getContentPane().getComponent(i);
                    if (c instanceof JTextField) {
                        JTextField field = (JTextField) c;
                        field.setText("");
                    }
                }
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_txtnomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaosair;
    private javax.swing.JButton botaosalvar;
    private javax.swing.JComboBox<String> cmbsituacao;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtcaracteristicas;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JFormattedTextField txtdatadesmama;
    private javax.swing.JFormattedTextField txtdatanascimento;
    private javax.swing.JFormattedTextField txtdatanascimentofilhote;
    public static javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnomemaemae;
    private javax.swing.JTextField txtnomepaimae;
    public static javax.swing.JTextField txtnumero;
    private javax.swing.JTextArea txtobservacao;
    private javax.swing.JTextField txtpai;
    private javax.swing.JTextField txtproprietario;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txtsituacao;
    // End of variables declaration//GEN-END:variables
}
